### PR TITLE
Creates AttackUtility class that calculates expected utility of an attack from one Unit to another.

### PR DESCRIPTION
**Pull request by punster94**
Additionally fixes Unit.takeAttack() and Attack constructor.

### CODE REVIEW

**Comment by punster94** [comment]
Check the TODOs.
My main concern with this involves integrating the Unit framework with the pathfinding / Node graph. There are a few things that need to change once we determine a clean way for at least the MainGame object to have a reference to the pathfinding graph so nodes can be assigned to units and vice-versa. I left a few things incomplete because of this, but their implementations should be straight-forward once a node is passed to the Unit's constructor.

**Comment by ListsOfArrays** [comment]
I say merge this in with the Node passed in. We really need a spawning area generated by the map generation class, but for now we can wing it with a method that passes a pair of spawning lists of Nodes for enemy/normal team. I can add that to this class if you want to this branch. The MainGame should really be in charge of the pathfinding. I can remove the PathFinding manager class and add pathfinding capability to the MainGame. Then, the subject would be instantiated by the MainGame, for debugging if we want that.

**Comment by ListsOfArrays** [comment]
Since we need references to the pathfinding class in the unit class, we could add the units to the MainGame, and since the pathfinding will be a component on the MainGame, we could fetch the units from there. It won't be as clean as it could be, but it will work for now. That way, we don't have to worry about singleton-like behavior for MainGame.

**Comment by ListsOfArrays** [comment]
We can actually bin the items in the MainGame object, that will be cleaner actually.

**Comment by ListsOfArrays** [comment]
I'm going to merge this in, and I'll start a unit_integration branch.

**Pull request merged**
